# Generated by Django 2.1.15 on 2021-06-30 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservaR', models.DateTimeField(blank=True, null=True)),
                ('nombreM', models.ManyToManyField(to='core.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoR', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='amaterno',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='apaterno',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reservaR',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horaR',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='montoR',
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombreM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_medico', to='core.Hora'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_hora_reserva', to='core.Hora'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pago'),
        ),
    ]
