# Generated by Django 2.1.15 on 2021-07-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('rut', 'Hora')},
        ),
    ]
