# Generated by Django 2.1.15 on 2021-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(max_length=200, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=11, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sexo',
            field=models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('2', 'OTRO')], max_length=20, verbose_name='sexo'),
        ),
    ]
