# Generated by Django 2.1.15 on 2021-07-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210630_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_hora_medico', to='core.Hora', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
    ]
