# Generated by Django 2.1.15 on 2021-07-03 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210703_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Especialidad'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='montoR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombreMedico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Medico'),
        ),
    ]
