# Generated by Django 2.1.15 on 2021-06-30 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210629_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombreM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_medico', to='core.Medico'),
        ),
    ]
