# Generated by Django 2.1.15 on 2021-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210629_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=80, verbose_name='nombre'),
        ),
    ]
