# Generated by Django 2.1.15 on 2021-07-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210629_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='fecha_reservaR',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='apaterno',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombreM',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='montoR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hora',
            name='fecha',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='hora',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='apellidos',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_hora_medico', to='core.Hora'),
        ),
        migrations.RemoveField(
            model_name='hora',
            name='nombreM',
        ),
        migrations.AddField(
            model_name='hora',
            name='nombreM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombreM',
            field=models.CharField(blank=True, max_length=80, verbose_name='nombre medico'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fecha nacimiento'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
